apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    chart: 'templates'
    repoURL: 'https://github.com/onbit-uchenik/argocd-playground.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
