apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment1.name }}
  name: {{ .Values.deployment1.name }}
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.deployment1.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.deployment1.name }}
    spec:
      containers:
      - image: httpd
        imagePullPolicy: Always
        name: "{{ .Values.deployment1.name }}-container"
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30